### ISSUE TITLE
BROKEN DONT USE DEV BLAMES IT ON CONFIGS WITH 0 CHANGES LOL

### ISSUE THREAD

**Issue by sabotage93thctv** [Mustachedom/md-houserobberies#15]
AVOID ITS BUGGED TO DEATH DEV JUST GETS CHEEKY AND CANT ADMIT THERES A ISSUE EVEN WHEN SHOWN THE LUA HE BLAMES AND SAYS WE HAVE CHANGED WAS REPLACED AND LOOKED AT TO BE A EXACT MATCH TO THE ORIGINAL GUY COULDNT SIMPLY ADMIT ITS A ISSUE ON HIS END SIGN OF A BAD DEV

**Comment by Mustachedom** [comment]
You're just mad I'm not fixing YOUR issue, it's not broken. YOUR PS DISPATCH HAS THE ERROR

not this script. Go learn how to read an error and check your issue, with ps-dispatch

**Comment by Mustachedom** [comment]
Also can't admit when I'm wrong? I absolutely can, I have no issues being wrong. Being wrong is how we learn. 

In this instance I'm not wrong, and I won't admit im wrong because your error is for ps-dispatch, not md-houserobberies. If it was my error, then would say the name of this script not ps-dispatch. 

You're angry as hell at being told you're wrong and to check your error. You have an insane attitude, I highly suggest reaching out to a therapist to help with those issues. Fivem shouldn't be getting you this worked up.

**Comment by Mustachedom** [comment]
![image](https://github.com/user-attachments/assets/99231004-762d-43d6-81a5-a0cc2e5461e9)

Now let's look at your issue. 

It clearly states you have a nil value named Config in which script?

Oh right ps-dispatch

Now let's look at where you went

![image](https://github.com/user-attachments/assets/5ff90fae-9962-45c4-881f-9611bf12c2ba)

You went to the correct line and there is a reference to the Config

So instead of checking your ps-dispatch config you decided to berate me, be extremely rude, and blame my script for an issue that doesn't exist in the script.

**Comment by Mustachedom** [comment]
As for the cheeky comment

Absolutely, I have spent a lot of time helping people fix their stuff, been extremely active in multiple discords helping new devs learn, released everything I've written for free, and the only requirement I've needed was to be treated with basic human respect. So when people are rude and disrespectful I absolutely will be cheeky because I'll just dedicate the time it would take to explain your issue to someone who is appreciative 

So cheers

**Comment by sabotage93thctv** [comment]
LOL SEE U CAN EVEN POST IT BUT NOT READ IT AS YOU WILL SEE THE ISSUE THATS BEEN BLAMED IS IMPOSSIBLE IF ITS NOT BEEN CHANGED

JUST PROVED MY POINT MORE

**Comment by Mustachedom** [comment]
I literally don't know how I can explain this more clearly. 

You break into a house

It alerts the police using ps-dispatch

The export calls to ps-dispatch

YOUR ps-dispatch throws an error FOR ITS CONFIG

This is not a md-houserobberies issue

It's a ps-dispatch issue

And to further prove a point, choose a build

1) brand new qb
2) old qb and I'll send a video of it working

**Comment by sabotage93thctv** [comment]
FUNNY BOTH DEVS ARE DOING THE STANDARD YOU BROKE IT TRICK THEN YOU EVEN CHECK TO BE SAFE AND THE LUA IS A EXACT MATCH TO A FRESH DOWNLOAD SO CLEARLY ITS NOT BEEN CHANGED/BROKE LIKE YOU SAY ITS ENFURIATING WHEN PEOPLE BLAME YOU BUT DONT LOOK AT A BASIC FACT IF ITS NOT BEEN CHANGED ITS CLEARLY A SCRIPT ERROR AND ITS FUNNY OTHER BUGS LIKE FALLING OUT OF ROBBERIES ARE HAPPENING WHICH OTHERS ARE ALSO HAVING THE SAME ISSUES WITH

**Comment by Mustachedom** [comment]
listen, i dont need to prove shit. I told you that this IS NOT AN ISSUE with md-houserobberies

IT IS an issue with ps-dispatch

YOU are the ONLY one to have reported this issue

and the house falling through is fixed with clearing your cache.

**Comment by sabotage93thctv** [comment]
LOL CLEARING CASHE IM DEAD HERE FUNNY THATS ONE OF THE THINGS I DO OFTEN AFTER WORKING ON MAPS NEVER CHANGED A THING

**Comment by Mustachedom** [comment]
![Screenshot 2024-09-15 205051](https://github.com/user-attachments/assets/0bfe8e7c-7d7d-4d19-96f9-2970526b319d)


fresh off git for md-houserobberies and ps-dispatch
the only thing i changed was removing the disable for breaking into the house if your police so i can test the alert

and they work.

its not me trying to "prove" anything to you. Its a you issue

and btw ive seen clearing cache and updating qb-interiors work. so before you laugh at something that has worked, fix your ps-dispatch

**Comment by Mustachedom** [comment]
as i have shown it does work as intended, the issue you are facing can be fixed with an update to ps-dispatch and is in no way related to this script I will stop replying. Reacting the way you are is no way to get adequate help from anyone.

**Comment by sabotage93thctv** [comment]
thats why i have tryed to explain from the start i have checked the exact luas even you pointed i was in the correct one even thought might be something my vs is not showing so i replaced it and still had the problems i did all this way before going to the point of a issue thats why when i confirm i have done something then get told thats the problem again and again theres littraly no way to prove to you even when you see i have done the correct things crazy

**Comment by sabotage93thctv** [comment]
when anyone else has this same issue just remember this is how he reacted  good dev lol

**Comment by Mustachedom** [comment]
And I have been saying from the start

This is not a md-houserobberies issue

If it was the error would pop up as md-houserobberies. When people read this they will see you as an insane asshole. 

I love helping and have built an entire community around helping new devs. 

I just don't work with people who are angry and spiteful and not willing to actually read. 

If that makes me a bad dev or an asshole then so be it. If there is no way to replicate it on my side, no other reports of this, and the error isn't from my script than how am I going to help. 

You have a global Config value as nil. That means ps-dispatches Config is not being read. ps-dispatch must be behind the issue. The export sends no values so it can't be something my script is sending to it.

**Comment by sabotage93thctv** [comment]
again had multiple errors from the script guy wont admit it is a issue caused by his script he would rather message the devs of other scripts and get me banned from there shit when not a rude word was spoken mans a child and funny after we look up your littlew friend funny 1of1 servers has some reviews saying this is how yous react

**Comment by Annalouu** [comment]
Honestly just stop, you are being a clown at this point.

**Comment by sabotage93thctv** [comment]
Broken ass script by a dev who can’t read two confugs the same and admit it’s not a problem with the config it’s his script
Sent from my iPhone

On 16 Sep 2024, at 10:57, Annastasia ***@***.***> wrote:

﻿

Honestly just stop, you are being a clown at this point.

**Comment by Annalouu** [comment]
The level of entitelmennt / Stupidity that radiates from you is breaking my stupidometer.. cant get any readings

**Comment by sabotage93thctv** [comment]
love your reply frsh out the dev toilet and your allready sinking back in ;)

**Comment by CarlBishop** [comment]
Mustachedom, is there a way to ban him from your github repo?
He is very limited, he reply the same way to every issue he open on every repo (take a look to the projectslot repos.

**Comment by sabotage93thctv** [comment]
yeah because devs like you cant admit when your script has a error are you moronic if a lua has no challenges and even gets replaced for a exact match from a fresh download with clearly no edits its clear all your doing is trying to blame the dev and not look at hard facts that no changes have been made and grooved it thats why you guys hate it when yus try to treat people like there dumb and deflect from the fact you have defective code in your script then you blame other resources as a set up so if we ask them they dont even reply close the ticket and ban me proving how shitty you guys are and cant admit to flaws

**Comment by Mustachedom** [comment]
i will absolutely admit when my script has an error

its pretty easy to prove what script has an error.

You have an error in ps-dispatch. YOUR PS DISPATCH CAN NOT READ THE CONFIG.

Can you explain to me how MY script is causing PS-DISPATCH to not read ps-dispatch's config?

**Comment by Mustachedom** [comment]
![Screenshot 2024-09-16 131047](https://github.com/user-attachments/assets/7dbba427-00bb-4914-9359-df8ce18ebb1a)
![Screenshot 2024-09-16 131117](https://github.com/user-attachments/assets/491bd934-b46d-4c58-9d16-85be76cb29e1)
![Screenshot 2024-09-16 131228](https://github.com/user-attachments/assets/8a3c6351-74c8-4d43-ba2f-76e6e35c8d03)


as you can see a fresh build

only things that are not from base qb
1. ox_lib ( downloaded latest release)
2. ps-dispatch ( downloaded source code from git)
3. md-houserobberies (only changed Config.oxtarget to false, removed job checks in the client to allow me to break in and see the dispatch alerts)

it works on an old qb build, it works on a brand new build, it works on a build 2 months old. 

I have recieved 0 errors and no falling through the map.

the way exports work is a script has a function. for example HouseRobbery()

then you create an export for that function which allows other scripts to use said function.

it acts like a TriggerEvent and leaves which script its working with and does what the function tells it to and returns the values if needed

once md-houserobberies triggers the export it goes to ps-dispatch

you have an error because your ps-dispatch can not read the config. this is not caused by md-houserobberies because thats simply not how this code works.

if there were a way to fix your error with md-houserobberies, i would tell you. Your issue is not related to md-houserobberies.

it is because your Config is coming up as nil which means nothing. Config does not exist for your ps-dispatch. 

at this point no matter what we say you're just going to blame this as breaking your config of a completely different script which even though isnt happening, you will do what you do. 


Its people like you that really makes me debate even offering support and helping people. Its a free script, your actual issue isnt from this script, you act like a lunatic when you're told the issue and blame me. Say Ive seen you've done it right ( even though the only screenshot you posted was the line of the error and NOT the config where its been shown is the issue.

I just have to remember that there is 10000s of devs who are willing to listen and learn and the small minority are like you.

**Comment by Mustachedom** [comment]
![Screenshot 2024-09-16 134040](https://github.com/user-attachments/assets/460f7071-f12c-44f4-bfe4-4aad564932b3)
i actually was able to recreate your issue

what i had to do to recreate the error is 
![Screenshot 2024-09-16 134135](https://github.com/user-attachments/assets/47407562-bfe7-4c5d-acc0-38c68775164b)


break a table in the config of ps-dispatch

**Comment by RazerGhost** [comment]
@sabotage93thctv shut up and go fix your config file. Nobody needs you to say/type meaningless words which are in fact inaccurate and won't help your moronic mind in getting fixed what's needed to be fixed in YOUR ps-dispacth config because YOU broke it and there is NO ISSUE with md-houserobberies.

**Comment by xSisyphusx** [comment]
@sabotage93thctv  -  You now have 5 different devs joining this thread to inform you that you're a complete moron. Your entitlement and inability to have a healthy discourse, rather than acting like a child that can't have ice cream is beyond something I would assume is a mental illness; and I suggest professional help. 

You have opened issues in several reputable developer github repos simply to accost them with your poor grammar, and even worse spelling; leading me to believe that you are either 15 years old and uneducated, OR you are an adult that watched "How To Code" on Youtube, and thinks that being a Config Dev allows them the right to speak to actual developers in this manner. 

If you think that something is broken @sabotage93thctv, the script is open source, feel free to open a pull request, or stfu.

@Mustachedom => md-houserobberies has been tested in my 2.5 Build and is working 100% without issue. Thank you for being such a selfless person, and releasing scripts like this to the public for free. You're incredible brother! <3

**Comment by Mustachedom** [comment]
![Screenshot 2024-09-17 010923](https://github.com/user-attachments/assets/138d1303-ad1c-4753-823c-702ed1f28d5d)
and would you look at that, an error format in your ps-dispatch config, which is breaking the script.

so while you were yelling, berating me, insulting me all while me saying over and over again that its an error in your ps-dispatch config, I was correct.

Ill take my apology now

**Comment by Mustachedom** [comment]
@xSisyphusx i'll always release for free because good people like you  deserve decent scripts for free :)

**Comment by Annalouu** [comment]
Bravo went dark lmao
